export const AUDIT_ACTIONS = {
  CREATOR_SIGNED_UP: 'CREATOR_SIGNED_UP',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_CONFIRMED: 'PASSWORD_RESET_CONFIRMED',
  PROGRAM_CREATED: 'PROGRAM_CREATED',
  PROGRAM_UPDATED: 'PROGRAM_UPDATED',
  PROGRAM_DELETED: 'PROGRAM_DELETED',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_UPDATED: 'SESSION_UPDATED',
  SESSION_DELETED: 'SESSION_DELETED',
  SESSIONS_REORDERED: 'SESSIONS_REORDERED',
  SESSIONS_IMPORTED: 'SESSIONS_IMPORTED',
  UPLOAD_URL_CREATED: 'UPLOAD_URL_CREATED',
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export const AUDIT_TARGET_TYPES = {
  CREATOR: 'CREATOR',
  PROGRAM: 'PROGRAM',
  SESSION: 'SESSION',
  BULK_IMPORT: 'BULK_IMPORT',
  UPLOAD: 'UPLOAD',
} as const

export type AuditTargetType = (typeof AUDIT_TARGET_TYPES)[keyof typeof AUDIT_TARGET_TYPES]
